[package]
name = "ops-tool"
version = "0.1.0"
authors = ["Iain Earl <synapse791@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "2.0"
reqwest =  { version = "0.10", features = ["blocking"] }
structopt = "0.3"
semver = "0.9"
zip = "0.5"
